import type { EventCategory, EventLanguage } from '../constants';
import type { BookingConfiguration, EntryType } from '../booking/types';
import type { EventWithRelations } from './types';

/**
 * In-memory dataset mirroring supabase/seed.sql. This backs the mock repository
 * so the app renders, builds and is E2E-testable without a live Supabase. It is
 * NOT invented data hiding a missing API — it is the same catalogue the seed
 * inserts, kept here as the dev/offline fixture behind the repository adapter.
 * Images are null to exercise the fallback-card pipeline (we never scrape art).
 */

interface Org {
  id: string;
  name: string;
  slug: string;
  city: string;
  verified: boolean;
  bio: string;
}
interface Ven {
  id: string;
  name: string;
  city: string;
  address: string;
  lat: number;
  lng: number;
}

const orgs: Record<string, Org> = {
  telugu: {
    id: 'org-telugu',
    name: 'Telugu Association Netherlands',
    slug: 'telugu-association-nl',
    city: 'Amstelveen',
    verified: true,
    bio: 'Volunteer-run community bringing Telugu families in the Netherlands together for cultural and festival events.',
  },
  gujarati: {
    id: 'org-gujarati',
    name: 'Gujarati Samaj Nederland',
    slug: 'gujarati-samaj-nl',
    city: 'Amsterdam',
    verified: true,
    bio: 'The home of Garba, Diwali and Gujarati culture in the Randstad since 2009.',
  },
  desibeats: {
    id: 'org-desibeats',
    name: 'DesiBeats Events',
    slug: 'desibeats',
    city: 'Amsterdam',
    verified: true,
    bio: 'Bollywood and desi party nights across Amsterdam and Rotterdam. Big sound, bigger dancefloors.',
  },
  sanatan: {
    id: 'org-sanatan',
    name: 'Sanatan Dharm Sabha Utrecht',
    slug: 'sanatan-utrecht',
    city: 'Utrecht',
    verified: false,
    bio: 'Temple committee organising aarti, Ganesh Chaturthi and Diwali celebrations for the Utrecht community.',
  },
  bengali: {
    id: 'org-bengali',
    name: 'Bengali Cultural Association NL',
    slug: 'bengali-cultural-nl',
    city: 'Den Haag',
    verified: true,
    bio: 'Durga Puja, Rabindra Sangeet evenings and Bengali food festivals in Den Haag.',
  },
  punjabi: {
    id: 'org-punjabi',
    name: 'Punjabi Virsa Netherlands',
    slug: 'punjabi-virsa-nl',
    city: 'Rotterdam',
    verified: false,
    bio: 'Bhangra nights, Vaisakhi and Punjabi culture across Rotterdam and beyond.',
  },
  tamil: {
    id: 'org-tamil',
    name: 'Tamil Sangam Nederland',
    slug: 'tamil-sangam-nl',
    city: 'Eindhoven',
    verified: false,
    bio: 'Tamil cultural evenings, Pongal and classical music for the Eindhoven community.',
  },
  hasee: {
    id: 'org-hasee',
    name: 'Hasee Comedy Club',
    slug: 'hasee-comedy',
    city: 'Amsterdam',
    verified: true,
    bio: 'The desi comedy night for the Netherlands. English and Hinglish stand-up, monthly.',
  },
};

const vens: Record<string, Ven> = {
  melkweg: {
    id: 'ven-melkweg',
    name: 'Melkweg',
    city: 'Amsterdam',
    address: 'Lijnbaansgracht 234a',
    lat: 52.3648,
    lng: 4.8814,
  },
  paradiso: {
    id: 'ven-paradiso',
    name: 'Paradiso',
    city: 'Amsterdam',
    address: 'Weteringschans 6-8',
    lat: 52.3622,
    lng: 4.8836,
  },
  afas: {
    id: 'ven-afas',
    name: 'AFAS Live',
    city: 'Amsterdam',
    address: 'ArenA Boulevard 590',
    lat: 52.3126,
    lng: 4.9447,
  },
  meervaart: {
    id: 'ven-meervaart',
    name: 'De Meervaart',
    city: 'Amsterdam',
    address: 'Meer en Vaart 300',
    lat: 52.3567,
    lng: 4.8067,
  },
  p60: {
    id: 'ven-p60',
    name: 'P60',
    city: 'Amstelveen',
    address: 'Stationsplein 21',
    lat: 52.3021,
    lng: 4.859,
  },
  tivoli: {
    id: 'ven-tivoli',
    name: 'TivoliVredenburg',
    city: 'Utrecht',
    address: 'Vredenburgkade 11',
    lat: 52.093,
    lng: 5.1155,
  },
  ahoy: {
    id: 'ven-ahoy',
    name: 'Rotterdam Ahoy',
    city: 'Rotterdam',
    address: 'Ahoyweg 10',
    lat: 51.8858,
    lng: 4.488,
  },
  doelen: {
    id: 'ven-doelen',
    name: 'De Doelen',
    city: 'Rotterdam',
    address: 'Schouwburgplein 50',
    lat: 51.9235,
    lng: 4.472,
  },
  effenaar: {
    id: 'ven-effenaar',
    name: 'Effenaar',
    city: 'Eindhoven',
    address: 'Dommelstraat 2',
    lat: 51.44,
    lng: 5.482,
  },
  zuider: {
    id: 'ven-zuider',
    name: 'Zuiderstrandtheater',
    city: 'Den Haag',
    address: 'Houtrustweg 505',
    lat: 52.108,
    lng: 4.256,
  },
  pijp: {
    id: 'ven-pijp',
    name: 'Buurthuis De Pijp',
    city: 'Amsterdam',
    address: 'Tweede van der Helststraat 66',
    lat: 52.354,
    lng: 4.893,
  },
  cultuur: {
    id: 'ven-cultuur',
    name: 'Cultuurhuis Den Haag',
    city: 'Den Haag',
    address: 'Spui 150',
    lat: 52.0767,
    lng: 4.316,
  },
};

interface Raw {
  id: string;
  org: keyof typeof orgs;
  ven: keyof typeof vens;
  title: string;
  slug: string;
  description: string;
  category: EventCategory;
  sub: string;
  start: string;
  end: string;
  minC: number | null;
  maxC: number | null;
  free: boolean;
  langs: EventLanguage[];
  age: string;
  featured: boolean;
  family: boolean;
  tags: string[];
  sold_out?: boolean;
}

const raw: Raw[] = [
  {
    id: 'ev-01',
    org: 'desibeats',
    ven: 'afas',
    title: 'Sufi Night with Kavita Seth',
    slug: 'sufi-night-kavita-seth',
    description: 'An evening of soulful Sufi and Bollywood classics with a live orchestra.',
    category: 'concert',
    sub: 'Sufi / Bollywood',
    start: '2026-10-24T18:00:00Z',
    end: '2026-10-24T22:00:00Z',
    minC: 3500,
    maxC: 8500,
    free: false,
    langs: ['Hindi', 'Urdu'],
    age: '16+',
    featured: true,
    family: false,
    tags: ['live music', 'sufi', 'bollywood'],
  },
  {
    id: 'ev-02',
    org: 'punjabi',
    ven: 'ahoy',
    title: 'Punjabi Live: Bhangra Arena',
    slug: 'punjabi-live-bhangra-arena',
    description: 'A high-energy Punjabi live concert with dhol, bhangra crews and a full band.',
    category: 'concert',
    sub: 'Punjabi',
    start: '2026-11-14T19:00:00Z',
    end: '2026-11-14T23:30:00Z',
    minC: 4500,
    maxC: 12000,
    free: false,
    langs: ['Punjabi', 'Hindi'],
    age: 'All ages',
    featured: true,
    family: false,
    tags: ['bhangra', 'live', 'arena'],
  },
  {
    id: 'ev-03',
    org: 'tamil',
    ven: 'tivoli',
    title: 'Carnatic Classical Evening',
    slug: 'carnatic-classical-evening',
    description: 'An intimate Carnatic vocal and violin recital. Seated, all welcome.',
    category: 'concert',
    sub: 'Carnatic',
    start: '2026-09-27T18:30:00Z',
    end: '2026-09-27T21:00:00Z',
    minC: 2000,
    maxC: 3500,
    free: false,
    langs: ['Tamil', 'Telugu'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['classical', 'carnatic'],
  },
  {
    id: 'ev-04',
    org: 'desibeats',
    ven: 'melkweg',
    title: 'Bollywood Saturdays',
    slug: 'bollywood-saturdays-oct',
    description:
      'The monthly Bollywood and desi party. Two rooms: Bollywood classics and desi house.',
    category: 'party',
    sub: 'Bollywood',
    start: '2026-10-10T21:00:00Z',
    end: '2026-10-11T03:00:00Z',
    minC: 1500,
    maxC: 2500,
    free: false,
    langs: ['Hindi', 'English'],
    age: '18+',
    featured: true,
    family: false,
    tags: ['nightlife', 'bollywood', 'dance'],
  },
  {
    id: 'ev-05',
    org: 'desibeats',
    ven: 'effenaar',
    title: 'Desi House Eindhoven',
    slug: 'desi-house-eindhoven',
    description: 'Desi house and Afro-desi fusion night with resident DJs.',
    category: 'party',
    sub: 'Desi House',
    start: '2026-09-19T21:00:00Z',
    end: '2026-09-20T02:00:00Z',
    minC: 1800,
    maxC: 1800,
    free: false,
    langs: ['English', 'Hindi'],
    age: '18+',
    featured: false,
    family: false,
    tags: ['nightlife', 'house'],
  },
  {
    id: 'ev-06',
    org: 'desibeats',
    ven: 'doelen',
    title: 'Diwali After-Party',
    slug: 'diwali-after-party-rotterdam',
    description: 'The official Diwali after-party. Dress to impress, festive dancefloor.',
    category: 'party',
    sub: 'Bollywood',
    start: '2026-11-08T22:00:00Z',
    end: '2026-11-09T04:00:00Z',
    minC: 2000,
    maxC: 3000,
    free: false,
    langs: ['Hindi', 'English'],
    age: '18+',
    featured: true,
    family: false,
    tags: ['diwali', 'nightlife'],
  },
  {
    id: 'ev-07',
    org: 'desibeats',
    ven: 'p60',
    title: 'Retro Bollywood Night',
    slug: 'retro-bollywood-night',
    description: 'Golden-era Bollywood, 90s and 2000s throwbacks all night.',
    category: 'party',
    sub: 'Retro',
    start: '2026-08-15T21:00:00Z',
    end: '2026-08-16T02:00:00Z',
    minC: 1500,
    maxC: 2000,
    free: false,
    langs: ['Hindi'],
    age: '18+',
    featured: false,
    family: false,
    tags: ['retro', 'throwback'],
  },
  {
    id: 'ev-08',
    org: 'gujarati',
    ven: 'meervaart',
    title: 'Navratri Garba Night 1',
    slug: 'navratri-garba-night-1',
    description:
      'Traditional Garba and Dandiya Raas with live dhol. Bring your sticks or buy at the door.',
    category: 'garba_dandiya',
    sub: 'Garba',
    start: '2026-10-11T18:30:00Z',
    end: '2026-10-11T23:30:00Z',
    minC: 1200,
    maxC: 2000,
    free: false,
    langs: ['Gujarati', 'Hindi'],
    age: 'All ages',
    featured: true,
    family: true,
    tags: ['navratri', 'garba', 'dandiya'],
  },
  {
    id: 'ev-09',
    org: 'gujarati',
    ven: 'meervaart',
    title: 'Navratri Garba Weekend Special',
    slug: 'navratri-garba-weekend',
    description: 'The big weekend Garba with a live orchestra from Gujarat and a food court.',
    category: 'garba_dandiya',
    sub: 'Garba',
    start: '2026-10-17T18:30:00Z',
    end: '2026-10-18T00:00:00Z',
    minC: 1500,
    maxC: 2500,
    free: false,
    langs: ['Gujarati', 'Hindi'],
    age: 'All ages',
    featured: true,
    family: true,
    tags: ['navratri', 'garba', 'live orchestra'],
  },
  {
    id: 'ev-10',
    org: 'tamil',
    ven: 'effenaar',
    title: 'Dandiya Dhamaal Eindhoven',
    slug: 'dandiya-dhamaal-eindhoven',
    description: 'A friendly community Dandiya night for all ages in Eindhoven.',
    category: 'garba_dandiya',
    sub: 'Dandiya',
    start: '2026-10-18T18:00:00Z',
    end: '2026-10-18T22:30:00Z',
    minC: 1000,
    maxC: 1500,
    free: false,
    langs: ['Gujarati', 'Hindi'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['dandiya', 'community'],
  },
  {
    id: 'ev-11',
    org: 'telugu',
    ven: 'meervaart',
    title: 'Diwali Gala 2026',
    slug: 'diwali-gala-2026',
    description: 'A grand Diwali gala: cultural performances, dinner and dancing. Family-friendly.',
    category: 'diwali',
    sub: 'Gala',
    start: '2026-11-07T17:00:00Z',
    end: '2026-11-07T23:00:00Z',
    minC: 3000,
    maxC: 6000,
    free: false,
    langs: ['Telugu', 'Hindi', 'English'],
    age: 'All ages',
    featured: true,
    family: true,
    tags: ['diwali', 'gala', 'dinner'],
  },
  {
    id: 'ev-12',
    org: 'sanatan',
    ven: 'pijp',
    title: 'Community Diwali Mela',
    slug: 'community-diwali-mela',
    description: 'A free Diwali mela with diya lighting, stalls, and kids activities.',
    category: 'diwali',
    sub: 'Mela',
    start: '2026-11-01T15:00:00Z',
    end: '2026-11-01T20:00:00Z',
    minC: 0,
    maxC: 0,
    free: true,
    langs: ['Hindi', 'English'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['diwali', 'mela', 'free'],
  },
  {
    id: 'ev-13',
    org: 'bengali',
    ven: 'zuider',
    title: 'Diwali Cultural Evening',
    slug: 'diwali-cultural-evening-denhaag',
    description: 'Classical dance, music and a lamp-lighting ceremony to celebrate Diwali.',
    category: 'diwali',
    sub: 'Cultural',
    start: '2026-11-06T18:00:00Z',
    end: '2026-11-06T21:30:00Z',
    minC: 1500,
    maxC: 2500,
    free: false,
    langs: ['Bengali', 'Hindi'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['diwali', 'dance'],
  },
  {
    id: 'ev-14',
    org: 'desibeats',
    ven: 'melkweg',
    title: 'Holi Festival of Colours 2027',
    slug: 'holi-festival-colours-2027',
    description:
      'The biggest Holi party with colours, water, DJs and street food. Outdoor + indoor.',
    category: 'holi',
    sub: 'Festival',
    start: '2027-03-06T12:00:00Z',
    end: '2027-03-06T18:00:00Z',
    minC: 2000,
    maxC: 3500,
    free: false,
    langs: ['Hindi', 'English'],
    age: 'All ages',
    featured: true,
    family: true,
    tags: ['holi', 'colours', 'festival'],
  },
  {
    id: 'ev-15',
    org: 'punjabi',
    ven: 'doelen',
    title: 'Holi Rangeela',
    slug: 'holi-rangeela-rotterdam',
    description: 'A family Holi celebration with organic colours and a live dhol.',
    category: 'holi',
    sub: 'Family',
    start: '2027-03-13T11:00:00Z',
    end: '2027-03-13T16:00:00Z',
    minC: 1500,
    maxC: 2000,
    free: false,
    langs: ['Hindi'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['holi', 'family'],
  },
  {
    id: 'ev-16',
    org: 'sanatan',
    ven: 'pijp',
    title: 'Ganesh Chaturthi Aarti',
    slug: 'ganesh-chaturthi-aarti',
    description:
      'Ganesh Chaturthi celebration with aarti, bhajan and prasad. All welcome, free entry.',
    category: 'temple',
    sub: 'Aarti',
    start: '2026-09-14T16:00:00Z',
    end: '2026-09-14T19:00:00Z',
    minC: 0,
    maxC: 0,
    free: true,
    langs: ['Hindi', 'Marathi'],
    age: 'All ages',
    featured: true,
    family: true,
    tags: ['ganesh', 'aarti', 'free'],
  },
  {
    id: 'ev-17',
    org: 'bengali',
    ven: 'cultuur',
    title: 'Durga Puja 2026',
    slug: 'durga-puja-2026',
    description:
      'Four days of Durga Puja: pushpanjali, cultural programmes and bhog. Free entry, donations welcome.',
    category: 'temple',
    sub: 'Durga Puja',
    start: '2026-10-09T09:00:00Z',
    end: '2026-10-12T21:00:00Z',
    minC: 0,
    maxC: 0,
    free: true,
    langs: ['Bengali', 'Hindi'],
    age: 'All ages',
    featured: true,
    family: true,
    tags: ['durga puja', 'bhog', 'free'],
  },
  {
    id: 'ev-18',
    org: 'sanatan',
    ven: 'tivoli',
    title: 'Diwali Lakshmi Puja',
    slug: 'diwali-lakshmi-puja',
    description: 'Community Lakshmi Puja on Diwali evening followed by prasad.',
    category: 'temple',
    sub: 'Puja',
    start: '2026-11-08T17:00:00Z',
    end: '2026-11-08T19:30:00Z',
    minC: 0,
    maxC: 0,
    free: true,
    langs: ['Hindi'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['diwali', 'puja', 'free'],
  },
  {
    id: 'ev-19',
    org: 'bengali',
    ven: 'cultuur',
    title: 'Rabindra Sangeet Evening',
    slug: 'rabindra-sangeet-evening',
    description: 'An evening of Tagore songs and poetry by local and guest artists.',
    category: 'cultural',
    sub: 'Music',
    start: '2026-09-20T18:00:00Z',
    end: '2026-09-20T20:30:00Z',
    minC: 1000,
    maxC: 1500,
    free: false,
    langs: ['Bengali'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['tagore', 'music'],
  },
  {
    id: 'ev-20',
    org: 'telugu',
    ven: 'p60',
    title: 'Kuchipudi & Bharatanatyam Showcase',
    slug: 'classical-dance-showcase',
    description: 'A showcase of South Indian classical dance by students and professionals.',
    category: 'cultural',
    sub: 'Dance',
    start: '2026-09-26T15:00:00Z',
    end: '2026-09-26T18:00:00Z',
    minC: 1200,
    maxC: 1800,
    free: false,
    langs: ['Telugu', 'Tamil', 'English'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['dance', 'classical'],
  },
  {
    id: 'ev-21',
    org: 'tamil',
    ven: 'effenaar',
    title: 'Pongal Celebration',
    slug: 'pongal-celebration',
    description: 'Tamil harvest festival with traditional food, music and games.',
    category: 'cultural',
    sub: 'Festival',
    start: '2027-01-16T11:00:00Z',
    end: '2027-01-16T16:00:00Z',
    minC: 800,
    maxC: 1200,
    free: false,
    langs: ['Tamil'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['pongal', 'harvest'],
  },
  {
    id: 'ev-22',
    org: 'hasee',
    ven: 'pijp',
    title: 'Hasee Comedy Night',
    slug: 'hasee-comedy-night-sep',
    description: 'Hinglish stand-up with four comedians. Sharp, relatable, desi-diaspora humour.',
    category: 'comedy',
    sub: 'Stand-up',
    start: '2026-09-13T19:00:00Z',
    end: '2026-09-13T21:30:00Z',
    minC: 1500,
    maxC: 2000,
    free: false,
    langs: ['English', 'Hindi'],
    age: '16+',
    featured: true,
    family: false,
    tags: ['comedy', 'standup'],
    sold_out: true,
  },
  {
    id: 'ev-23',
    org: 'hasee',
    ven: 'paradiso',
    title: 'Desi Roast Battle',
    slug: 'desi-roast-battle',
    description: 'Comedians roast each other and the audience. Not for the faint-hearted.',
    category: 'comedy',
    sub: 'Roast',
    start: '2026-10-25T20:00:00Z',
    end: '2026-10-25T22:00:00Z',
    minC: 1800,
    maxC: 1800,
    free: false,
    langs: ['English'],
    age: '18+',
    featured: false,
    family: false,
    tags: ['comedy', 'roast'],
  },
  {
    id: 'ev-24',
    org: 'bengali',
    ven: 'zuider',
    title: 'Bengali Food Festival',
    slug: 'bengali-food-festival',
    description: 'A pop-up food festival with 20 stalls of Bengali and East Indian cuisine.',
    category: 'food',
    sub: 'Festival',
    start: '2026-09-28T11:00:00Z',
    end: '2026-09-28T18:00:00Z',
    minC: 500,
    maxC: 500,
    free: false,
    langs: ['Bengali', 'English'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['food', 'festival'],
  },
  {
    id: 'ev-25',
    org: 'gujarati',
    ven: 'pijp',
    title: 'Street Food Bazaar',
    slug: 'desi-street-food-bazaar',
    description: 'Chaat, dosa, biryani and mithai from home cooks and small vendors.',
    category: 'food',
    sub: 'Bazaar',
    start: '2026-08-30T12:00:00Z',
    end: '2026-08-30T19:00:00Z',
    minC: 0,
    maxC: 0,
    free: true,
    langs: ['Hindi', 'English'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['street food', 'bazaar', 'free'],
  },
  {
    id: 'ev-26',
    org: 'telugu',
    ven: 'p60',
    title: 'Kids Bollywood Dance Camp',
    slug: 'kids-bollywood-dance-camp',
    description:
      'A weekend dance camp for kids aged 6-12. All levels, performance on the last day.',
    category: 'family',
    sub: 'Kids',
    start: '2026-10-04T09:00:00Z',
    end: '2026-10-04T13:00:00Z',
    minC: 2500,
    maxC: 2500,
    free: false,
    langs: ['English', 'Hindi'],
    age: '6-12 yrs',
    featured: false,
    family: true,
    tags: ['kids', 'dance', 'camp'],
  },
  {
    id: 'ev-27',
    org: 'sanatan',
    ven: 'pijp',
    title: 'Family Storytelling: Ramayana',
    slug: 'family-storytelling-ramayana',
    description: 'Interactive storytelling of the Ramayana for children and parents.',
    category: 'family',
    sub: 'Storytelling',
    start: '2026-09-21T14:00:00Z',
    end: '2026-09-21T15:30:00Z',
    minC: 0,
    maxC: 0,
    free: true,
    langs: ['English', 'Hindi'],
    age: 'All ages',
    featured: false,
    family: true,
    tags: ['kids', 'storytelling', 'free'],
  },
  {
    id: 'ev-28',
    org: 'punjabi',
    ven: 'p60',
    title: 'Bhangra Dance Workshop',
    slug: 'bhangra-dance-workshop',
    description: 'Learn the basics of Bhangra in a fun two-hour workshop. No experience needed.',
    category: 'workshop',
    sub: 'Dance',
    start: '2026-09-12T17:00:00Z',
    end: '2026-09-12T19:00:00Z',
    minC: 1500,
    maxC: 1500,
    free: false,
    langs: ['Punjabi', 'English'],
    age: '16+',
    featured: false,
    family: false,
    tags: ['workshop', 'bhangra'],
  },
  {
    id: 'ev-29',
    org: 'tamil',
    ven: 'effenaar',
    title: 'Tabla for Beginners',
    slug: 'tabla-for-beginners',
    description: 'A beginner tabla workshop covering basic bols and rhythm. Instruments provided.',
    category: 'workshop',
    sub: 'Music',
    start: '2026-10-03T13:00:00Z',
    end: '2026-10-03T15:30:00Z',
    minC: 2000,
    maxC: 2000,
    free: false,
    langs: ['Hindi', 'English'],
    age: '12+',
    featured: false,
    family: true,
    tags: ['workshop', 'tabla', 'music'],
  },
  {
    id: 'ev-30',
    org: 'telugu',
    ven: 'cultuur',
    title: 'Desi Professionals Meetup',
    slug: 'desi-professionals-meetup',
    description:
      'Networking evening for South Asian professionals in tech, finance and healthcare.',
    category: 'networking',
    sub: 'Professional',
    start: '2026-09-25T17:30:00Z',
    end: '2026-09-25T20:00:00Z',
    minC: 0,
    maxC: 0,
    free: true,
    langs: ['English'],
    age: '18+',
    featured: false,
    family: false,
    tags: ['networking', 'professional', 'free'],
  },
];

/**
 * Booking and lineup overrides, keyed by slug. Everything not listed falls
 * back to the derivation below (paid → the organiser's own booking page, free
 * → nothing to book), which is what the MVP catalogue actually looks like.
 * The handful of entries here exist to keep every branch of the booking
 * service exercised in dev and in E2E.
 */
const BOOKING_OVERRIDES: Record<
  string,
  { entry?: EntryType; booking?: Partial<BookingConfiguration>; dress?: string }
> = {
  // Pilot organisers on DesiHub's own checkout. Degrades to their external
  // page when native ticketing is switched off (which is the default).
  'sufi-night-kavita-seth': {
    booking: { booking_type: 'desihub', provider: 'DesiHub' },
    dress: 'Smart casual / Indian formal',
  },
  'punjabi-live-bhangra-arena': {
    booking: { booking_type: 'desihub', provider: 'DesiHub' },
  },
  // Free, but the host wants an RSVP so they can size the room.
  'desi-professionals-meetup': {
    entry: 'registration',
    booking: {
      booking_type: 'free_registration',
      provider: 'the organiser',
      booking_url: 'https://desi-professionals.example.org/rsvp',
    },
  },
  // Cash on the night — the community-hall model.
  'carnatic-classical-evening': { entry: 'door' },
};

const LINEUPS: Record<string, { name: string; role: string }[]> = {
  'sufi-night-kavita-seth': [
    { name: 'Kavita Seth', role: 'Live artist' },
    { name: 'Kanishk Seth', role: 'Producer' },
  ],
  'punjabi-live-bhangra-arena': [
    { name: 'Jazzy B', role: 'Live artist' },
    { name: 'DJ Chetas', role: 'DJ' },
    { name: 'Dhol Foundation', role: 'Dhol & percussion' },
  ],
  'bollywood-saturdays-oct': [
    { name: 'DJ Suketu', role: 'DJ' },
    { name: 'DJ Amyra', role: 'DJ' },
  ],
};

/**
 * A plausible organiser booking page. Fictional `.example.org` hosts, on
 * purpose: the mock catalogue must never point a real visitor at a real
 * third-party site we have no relationship with.
 */
function mockBookingUrl(orgSlug: string, eventSlug: string): string {
  return `https://${orgSlug}.example.org/events/${eventSlug}`;
}

function buildBooking(r: Raw, orgSlug: string, entry: EntryType): BookingConfiguration {
  const override = BOOKING_OVERRIDES[r.slug]?.booking ?? {};
  const base: BookingConfiguration = {
    event_id: r.id,
    booking_type: entry === 'paid' ? 'external_url' : 'none',
    provider: entry === 'paid' ? orgs[r.org]!.name : null,
    booking_url: entry === 'paid' ? mockBookingUrl(orgSlug, r.slug) : null,
    external_event_id: null,
    status: r.sold_out ? 'sold_out' : 'available',
    metadata: {},
  };
  const merged = { ...base, ...override };
  // A DesiHub-ticketed event still keeps its organiser link, so turning native
  // ticketing off leaves a working booking route rather than a dead card.
  if (merged.booking_type === 'desihub' && !override.booking_url) {
    merged.booking_url = mockBookingUrl(orgSlug, r.slug);
  }
  return merged;
}

function buildEvent(r: Raw): EventWithRelations {
  const o = orgs[r.org]!;
  const v = vens[r.ven]!;
  const entry: EntryType = BOOKING_OVERRIDES[r.slug]?.entry ?? (r.free ? 'free' : 'paid');
  return {
    id: r.id,
    organiser_id: o.id,
    venue_id: v.id,
    title: r.title,
    slug: r.slug,
    description: r.description,
    category: r.category,
    sub_category: r.sub,
    image_url: null,
    poster_image_url: null,
    gallery: [],
    starts_at: r.start,
    ends_at: r.end,
    doors_at: null,
    is_free: r.free,
    entry_type: entry,
    min_price_cents: r.minC,
    max_price_cents: r.maxC,
    currency: 'EUR',
    languages: r.langs,
    age_policy: r.age,
    dress_code: BOOKING_OVERRIDES[r.slug]?.dress ?? null,
    lineup: (LINEUPS[r.slug] ?? []).map((a) => ({ ...a, image_url: null })),
    // Events with in-platform ticket_types sell through our own checkout
    // (Phase 3); external_ticket_url stays for the (currently none, in the
    // mock catalogue) case of an organiser who tickets elsewhere.
    external_ticket_url: null,
    status: r.sold_out ? 'sold_out' : 'published',
    featured: r.featured,
    family_friendly: r.family,
    tags: r.tags,
    seo_title: null,
    seo_description: null,
    highlights: null,
    terms: null,
    created_at: '2026-06-01T00:00:00Z',
    organiser: {
      id: o.id,
      name: o.name,
      slug: o.slug,
      verified: o.verified,
      city: o.city as never,
      logo_url: null,
    },
    venue: {
      id: v.id,
      name: v.name,
      city: v.city as never,
      address: v.address,
      lat: v.lat,
      lng: v.lng,
    },
    booking: buildBooking(r, o.slug, entry),
    ticketTypes: r.free
      ? []
      : [
          {
            id: `${r.id}-tt`,
            name: 'Standard',
            price_cents: r.minC ?? 0,
            quantity: 200,
            sold: r.sold_out ? 200 : 40,
            fee_mode: 'pass_on' as const,
            min_per_order: 1,
            max_per_order: 10,
          },
        ],
  };
}

export const MOCK_EVENTS: EventWithRelations[] = raw.map(buildEvent);
export const MOCK_ORGANISERS = orgs;
